export const INTEREST_CATEGORIES: Record<string, string[]> = {
  Technology: [
    "Artificial Intelligence",
    "Automation",
    "Blockchain",
    "Cloud Computing",
    "Computer Science",
    "Cybersecurity",
    "Data Science",
    "Fintech",
    "Information Technology",
    "Machine Learning",
    "Mobile development",
    "Robotics",
    "Software Engineering",
    "UI/UX design",
  ],

  Engineering: [
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Engineering",
    "Environmental Engineering",
    "Mechanical Engineering",
  ],

  Business_and_Economics: [
    "Accounting",
    "Business Administration",
    "Business and entrepreneurship",
    "Economics",
    "Finance",
    "Management",
    "Marketing",
  ],

  Health_and_Medicine: [
    "Dentistry",
    "Medicine",
    "Nursing",
    "Pharmacy",
    "Public Health",
    "Veterinary Science",
  ],

  Natural_Sciences: [
    "Agriculture",
    "Astronomy",
    "Biology",
    "Chemistry",
    "Environmental Science",
    "Geology",
    "Mathematics",
    "Physics",
    "Statistics",
  ],

  Arts_and_Design: [
    "Animation",
    "Art",
    "Design",
    "Fashion Design",
    "Film Studies",
    "Graphic design",
    "Music",
    "Theatre",
  ],

  Social_Sciences_and_Humanities: [
    "Anthropology",
    "Communications",
    "Education",
    "Geography",
    "History",
    "International Relations",
    "Journalism",
    "Law",
    "Linguistics",
    "Literature",
    "Media Studies",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Sociology",
    "Social Work",
    "Theology",
    "Urban Planning",
  ],

  General: ["Sports"],
};
